#!/bin/bash
set -e
set -o pipefail

SESSION_TYPE=x11
CAN_TYPE=false
if [[ -n "$WAYLAND_DISPLAY" ]]; then
  SESSION_TYPE=wayland
  export LPASS_CLIPBOARD_COMMAND=wl-copy
  if hash wtype; then
    CAN_TYPE=true
  fi
else
  if hash xvkbd || hash xdotool; then
    CAN_TYPE=true
  fi
fi

print-account-list() {
  lpass ls --format "%/as%ag - %an (%au) [%ai]" 2>&1
}

type-account-field() {
# Close stdout and stderr to stop this process from dying when the parent ends
  exec 1>/dev/null 2>/dev/null

  local value=$(lpass show --quiet "--${2}" "$1")
  case "$SESSION_TYPE" in
    x11)
      if hash xvkbd 2>/dev/null; then
        xvkbd -xsendevent -text "$value"
      else
        local active_window=$(xdotool getactivewindow)
        xdotool windowactivate --sync "$active_window" type --clearmodifiers "$value"
      fi
      ;;
    wayland)
      wtype "$value"
      ;;
  esac
}

copy-account-field() {
  lpass show --clip "--${2}" "$1" >/dev/null 2>/dev/null
}

open-account-url() {
  local url=$(lpass show --url "$1")
  if [[ -n "$url" ]]; then
    xdg-open "$url" >/dev/null 2>/dev/null
  else
    exit 2
  fi
}

is-actual-url() {
  local url="$1"
  if [[ -n "$url" && "$url" != " " && "$url" != "http://" && "$url" != "https://" ]]; then
    return 0
  else
    return 1
  fi
}

show-account-options() {
  local id="$1"

  if "$CAN_TYPE"; then
    echo ">> Type password [$id]"
    echo ">> Type username [$id]"
  fi

  echo ">> Copy password [$id]"
  echo ">> Copy username [$id]"

  url=$(lpass show --url "$id")
  if is-actual-url "$url"; then
    echo ">> Open $url [$id]"
    echo ">> Copy URL [$id]"
  fi

  echo ">> Copy ID [$id]"
}

is-entry-selected() {
  if [[ -n "$@" ]]; then
    return 0
  else
    return 1
  fi
}

id-in-selection() {
  echo "$1" | grep -oE '\[[0-9]+\]$' | tr -d '[]'
}

debug() {
  echo "$@" > /dev/stderr
}

if is-entry-selected "$1"; then
  selected="$1"

  id="$(id-in-selection "$selected")"

  if [[ -n "$id" ]]; then
    case "$selected" in
      '>> Type password'*)
        type-account-field "$id" password & ;;
      '>> Type username'*)
        type-account-field "$id" username & ;;
      '>> Copy password'*)
        copy-account-field "$id" password ;;
      '>> Copy username'*)
        copy-account-field "$id" username ;;
      '>> Copy URL'*)
        copy-account-field "$id" url ;;
      '>> Copy ID'*)
        copy-account-field "$id" id ;;
      '>> Open'*)
        open-account-url "$id" ;;
      *)
        show-account-options "$id" ;;
    esac
  else
    echo "Could not detect the entry ID of \"${selection}\""
    exit 1
  fi
else
  print-account-list
fi
